import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { defineBlogConfig } from 'vitepress-theme-neptu-blog/configs'
import type { BlogUserConfig, ThemeConfig } from 'vitepress-theme-neptu-blog'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export const PER_PAGE = 10

// ---------------------------------------------------------------------------
// Popular posts via Google Analytics 4.
// Requires GA_PROPERTY_ID and GA_CREDENTIALS_JSON environment variables.
// ---------------------------------------------------------------------------
export const popularPosts = {
  enabled: Boolean(
    process.env.GA_PROPERTY_ID && process.env.GA_CREDENTIALS_JSON
  ),
  // enabled: true, // force-enable for local demo without GA env vars
  sortBy: 'pageviews', // 'pageviews' | 'uniquePageviews' | 'avgTimeOnPage'
  dataSource: {
    provider: 'ga4' as const,
    propertyId: process.env.GA_PROPERTY_ID,
    credentialsJson: process.env.GA_CREDENTIALS_JSON,
    // dataPeriodDays: 30,  // days of data to fetch (default: 30)
    // dataLimit: 1000,     // max posts fetched from GA4 (default: 1000)
  },
} satisfies NonNullable<ThemeConfig['popularPosts']>

// ---------------------------------------------------------------------------
// Build-time post list options.
// `maxPreviewLength` is read by `loadPosts.data.ts` and `getAllPosts.ts` at
// data-loader time and must therefore live in code. Visual `postList` flags
// (showDate / showTags / ...) belong in `src/site.yaml` and override the
// rendered cards independently of this constant.
// ---------------------------------------------------------------------------
export const postList = {
  maxPreviewLength: 300,
}

export default async () => {
  const config: BlogUserConfig = {
    srcDir: path.resolve(__dirname, '../'),

    // -------------------------------------------------------------------------
    // Site identity — absolute public URL with protocol, no trailing slash.
    // Include VitePress `base` here too when the site is deployed under one.
    // Used for canonical links, sitemap, RSS feeds, Open Graph, JSON-LD,
    // hreflang, and robots.txt.
    // -------------------------------------------------------------------------
    siteUrl: 'https://myblog.org',

    // tailwindcss() and site-yaml hot-reload are injected automatically.
    // Add other Vite plugins here:
    // vite: { plugins: [myPlugin()] },

    head: [
      // Prevent auto-detection of phone numbers as links on iOS.
      ['meta', { name: 'format-detection', content: 'telephone=no' }],

      // Google Analytics 4 — replace G-XXXXXXXXXX with your Measurement ID.
      // ['script', { async: '', src: 'https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX' }],
      // ['script', {}, `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-XXXXXXXXXX');`],

      // Pagefind search UI assets (generated by the `pagefind` build step).
      ['link', { rel: 'stylesheet', href: '/pagefind/pagefind-ui.css' }],
      ['script', { src: '/pagefind/pagefind-ui.js' }],
    ],

    // -------------------------------------------------------------------------
    // Custom transform hooks — composed with the theme's built-in transformers.
    // The theme's transformers run first, then yours; this is standard VitePress.
    // For "before" semantics, use VitePress' `extends` mechanism.
    // -------------------------------------------------------------------------
    // async transformPageData(pageData, ctx) {
    //   pageData.frontmatter.customField = 'value'
    // },
    // async transformHead(ctx) {
    //   return [['meta', { name: 'custom', content: 'value' }]]
    // },
    // async buildEnd(siteConfig) { /* ... */ },

    // -------------------------------------------------------------------------
    // Developer-owned theme settings.
    //
    // Keep this block focused on:
    //   - technical wiring that needs code (env vars, derived values)
    //   - integrations the admin should not edit (search provider, analytics)
    //   - identifiers consumed by other settings (e.g. `repo`)
    //
    // Admin-editable presentation (nav, sidebar, footer, donate, publisher,
    // authors, socialMediaShares, icons, postList, postFooter, SEO toggles,
    // etc.) belongs in `src/site.yaml` (cross-locale) or
    // `src/<locale>/_site.yaml` (per-locale). See docs/CONFIG_LAYERS.md.
    // -------------------------------------------------------------------------
    themeConfig: {
      // Repository — drives the edit-link footer block and is referenced
      // from YAML via `${theme.repo}`.
      repo: 'https://github.com/your-org/your-blog',

      // Posts per page — referenced from code via the exported `PER_PAGE`.
      perPage: PER_PAGE,

      // Search provider config (Pagefind assets are wired in `head` above).
      search: {
        provider: 'pagefind',
        options: { bodyMarker: 'data-pagefind-body' },
      },

      // Popular posts — env-driven, must stay in code.
      popularPosts,
    },

  }

  return defineBlogConfig(config)
}
